export enum DocumentType {
    DriverLicense = 'driver-license',
    VehicleLicense = 'vehicle-license',
    VehicleInsurance = 'vehicle-insurance',
    StudentIdCard = 'student-id-card',
    InternalPassport = 'internal-passport',
    ForeignPassport = 'foreign-passport',
    TaxpayerCard = 'taxpayer-card',
    RefInternallyDisplacedPerson = 'reference-internally-displaced-person',
    BirthCertificate = 'birth-certificate',
    LocalVaccinationCertificate = 'local-vaccination-certificate',
    ChildLocalVaccinationCertificate = 'child-local-vaccination-certificate',
    InternationalVaccinationCertificate = 'international-vaccination-certificate',
    PensionCard = 'pension-card',
    ResidencePermitPermanent = 'residence-permit-permanent',
    ResidencePermitTemporary = 'residence-permit-temporary',
    EResidency = 'e-residency',
    EResidentPassport = 'e-resident-passport',
    UId = 'u-id',
    MilitaryBond = 'military-bond',
    OfficialCertificate = 'official-certificate',
    HousingCertificate = 'housing-certificate',
    EducationDocument = 'education-document',
    MarriageActRecord = 'marriage-act-record',
    DivorceActRecord = 'divorce-act-record',
    NameChangeActRecord = 'name-change-act-record',
    UserBirthCertificate = 'user-birth-certificate',
}
