export * from './generated/category/publicServiceCodes'

export * from './generated/publicServiceCode'

export enum PublicServiceKebabCaseCode {
    CriminalRecordCertificate = 'criminal-cert',
    ResidenceCert = 'residence-cert',
    ResidenceCertChildren = 'residence-cert-children',
    CourtCases = 'court-cases',
    CourtPenalties = 'court-penalties',
    Ok5Certificate = 'ok5-cert',
    Ok7Certificate = 'ok7-cert',
    ProperUser = 'proper-user',
    DiiaRadio = 'diia-radio',
    DiiaTv = 'diia-tv',
    DamagedProperty = 'damaged-property',
    DamagedPropertyRecovery = 'damaged-property-recovery',
    HousingCertificates = 'housing-certificates',
    MonetaryCompensation = 'monetary-compensation',
    EResidentPrivateEntrepreneur = 'e-resident-private-entrepreneur',
    EResidentPrivateEntrepreneurChanges = 'e-resident-private-entrepreneur-changes',
    EResidentStatusTermination = 'e-resident-status-termination',
    EResidentBankAccount = 'e-resident-bank-account',
    InternallyDisplacedPerson = 'internally-displaced-person',
    UnemploymentStatus = 'unemployment-status',
    UnemploymentStatusCanceling = 'unemployment-status-canceling',
    HomecomingIdentityCard = 'homecoming-identity-card',
    MilitaryBonds = 'military-bonds',
    VehicleCustomsClearance = 'vehicle-customs-clearance',
    VehicleReRegistration = 'vehicle-re-registration',
    InvincibilityPoints = 'invincibility-points',
    CustomsClearanceCalculator = 'customs-clearance-calculator',
    Mortgage = 'mortgage',
    CancelInternallyDisplacedPerson = 'cancel-internally-displaced-person',
    EditInternallyDisplacedPersonAddress = 'edit-internally-displaced-person-address',
    ResidenceRegistration = 'residence-registration',
    ChildResidenceRegistration = 'child-residence-registration',
    LedExchange = 'led-exchange',
    DroneArmy = 'drone-army',
    ReplacementDriverLicense = 'replacement-driver-license',
    Penalties = 'penalties',
    DepositGuaranteePayments = 'deposit-guarantee-payments',
    OfficeBadges = 'office-badges',
    OfficeOfficialSearch = 'office-official-search',
    OfficeOfficialWorkspace = 'office-official-workspace',
    OfficePolls = 'office-polls',
    Poll = 'poll',
    Debts = 'debts',
    Questionnaire = 'questionnaire',
    Marriage = 'marriage',
    Proposal = 'proposal',
}
